name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/project-1:latest
            ${{ secrets.DOCKER_USERNAME }}/project-1:${{ github.sha }}
      - name: SSH to Prod server & create app folder
        uses: appleboy/ssh-action@v1.0.3
        with:
                host: ${{ secrets.EC2_IP }}
                username: ubuntu
                key: ${{ secrets.EC2_KEY }}
                script: |
                 echo "Installing required packages & folders"
                 sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
                 sudo usermod -aG docker $USER
                 rm -rf ~/devops/docker-compose.yml
                 mkdir -p ~/project-1
            

      - name: Copy the docker-compose file
        uses: appleboy/scp-action@v1
        with:
                host: ${{ secrets.EC2_IP }}
                username: ubuntu
                key: ${{ secrets.EC2_KEY }}
                source: Docker-compose.yml
                target: ~/project-1
                overwrite: true

      # ✅ Deploy
      - name: SSH to EC2 & Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            chmod +x deploy.sh

            echo "🔐 Docker login"
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            sudo apt-get update -y
            sudo apt-get install docker-compose-plugin -y

            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            export DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}

            ./deploy.sh